[graph]
targets = [
    "aarch64-unknown-none",
    "riscv64gc-unknown-none-elf",
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
]
all-features = true

[advisories]
yanked = "deny"
unmaintained = "workspace"
unsound = "all"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.93

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
