//! Safe, bounded TOSA graph ingestion for `virtio-accel` providers.
//!
//! This crate validates a TOSA FlatBuffer before exposing zero-copy borrowed views. The public API
//! contains no generated FlatBuffers types and no unchecked accessors. Validation is deliberately
//! split into two layers:
//!
//! - [`parse`] enforces the serialization envelope, resource limits, stable TOSA 1.0 schema
//!   boundary, names, references, and operator/attribute correspondence;
//! - [`Model::validate_for`] exhaustively enforces the stable operator arities, operand kinds,
//!   ranks, profiles, extensions, level limits, attributes, compile-time constants, static shapes,
//!   control-flow signatures, and numerical parameter rules for a declared [`Target`]; and
//! - provider-specific capability and [`Op::CUSTOM`] policy can be layered through
//!   [`ModelValidator`].
//!
//! Semantic validation proves model legality; it does not execute tensor data or replace a
//! backend's runtime checks for data-dependent TOSA `REQUIRE` conditions.
//!
//! The checked-in schema is from TOSA Tools `v2026.05.0`. The tools release implements TOSA
//! specification 1.0.1 and appends draft TOSA 1.1 entries; [`parse`] accepts stable graph version
//! 1.0.0 and rejects those appended entries.

#![no_std]
#![deny(unsafe_code)]

extern crate alloc;

mod analysis;
mod artifact;
mod attribute;
mod capability;
// Generated by upstream `flatc` 25.2.10 from `schema/tosa.fbs`. The module is private, and every
// generated accessor is reached only after the generated verifier succeeds. See SAFETY.md.
#[allow(
    unsafe_code,
    unsafe_op_in_unsafe_fn,
    unknown_lints,
    dead_code,
    deprecated,
    unused_imports,
    non_camel_case_types,
    mismatched_lifetime_syntaxes,
    non_snake_case,
    non_upper_case_globals,
    clippy::extra_unused_lifetimes
)]
#[rustfmt::skip]
mod generated;
mod integer;
mod numeric;
mod runtime;
mod semantic;
mod specialize;
mod types;
mod validate;
mod view;

pub use analysis::{
    AnalysisError, AnalysisOptions, AnalysisSpan, AnalyzedBlock, AnalyzedOperator, AnalyzedRegion,
    AnalyzedValue, AnalyzedValueKind, BlockId, ConstantState, OperatorId, OptimizationHints,
    RegionId, RuntimeCondition, TosaAnalysis, ValueId,
};
pub use artifact::{
    ARTIFACT_FORMAT, ArtifactError, ExtensionSet, Level, LevelLimits, ProfileSet, Target,
    TargetError,
};
pub use attribute::{
    I32List, I32Values, NanPropagationMode, OpAttributes, ResizeMode, RoundingMode,
};
pub use capability::{
    CapabilityDescriptor, DTypeCapability, DTypeConstraints, GraphCapabilities, OperatorCapability,
    OperatorConstraints, RuntimeConditionSupport, TosaCapabilityProvider, ValueRoles,
};
pub use integer::{IntegerError, apply_scale_16, apply_scale_32, dot_i8_i32, rescale_i32_to_i8};
pub use numeric::{
    fp8e4m3_to_f32, fp8e5m2_to_f32, low_precision_storage_bytes, pack_int4, unpack_int4,
};
pub use runtime::{
    RuntimeError, RuntimeErrorKind, RuntimeValidation, RuntimeValue, validate_runtime_values,
};
pub use semantic::{
    OperandRole, SemanticError, SemanticErrorKind, SemanticValidator, validate_semantics,
};
pub use specialize::{
    CacheInsertError, SpecializationCache, SpecializationError, SpecializationKey,
    SpecializationKeyBuilder,
};
pub use types::{Arity, AttributeKind, DType, Op, Version};
pub use validate::{Error, Limits, NameKind, Resource, Stats, parse, parse_with_limits};
pub use view::{
    BasicBlock, BasicBlocks, Model, ModelValidator, Operator, Operators, Region, Regions, Shape,
    ShapeValues, Shapes, StringList, Tensor, Tensors,
};

/// TOSA schema source pinned into this crate.
pub const SCHEMA: &str = include_str!("../schema/tosa.fbs");

/// SHA-256 of [`SCHEMA`] as shipped by TOSA Tools `v2026.05.0`.
pub const SCHEMA_SHA256: &str = "a1d6383bdecddf9cc6a00c33e5a2fac7e8479dc560a9da2f68ba41da35e143f8";

/// Upstream TOSA Tools release from which [`SCHEMA`] was copied.
pub const SCHEMA_RELEASE: &str = "v2026.05.0";

#[cfg(test)]
mod tests;
