[package]
name = "virtio-accel-device"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Transport-neutral virtio accelerator device state"
readme = "README.md"

[dependencies]
virtio-accel-core.workspace = true
virtio-accel-proto.workspace = true
virtio-accel-transport.workspace = true
zerocopy.workspace = true

[dev-dependencies]
virtio-accel-mock.workspace = true
