#!/usr/bin/env python3
"""Validate the built virtio-accel.org tree.

``build.py`` curates the narrative docs out of ``docs/`` and ``README.md`` and
rewrites their cross-links, so a doc edit can produce a site that builds
cleanly and still links into nothing. This script is the check that turns that
into a pull-request failure instead of a broken page on the live site:

  1. Every page the table of contents promises exists.
  2. The standalone landing page really did overlay ``book/index.html``.
  3. Every relative reference in the generated HTML -- links, stylesheets,
     scripts, images, media, and ``srcset`` candidates -- resolves to a file
     that exists.

Only the site's own pages are crawled. The rustdoc tree under ``api/`` is
generated by ``cargo doc`` and is not ours to lint, so it is treated as a set
of link *targets* rather than as pages to crawl. When it is absent -- a local
``build.py --skip-rustdoc`` run -- links into it are skipped with a notice
rather than reported as dangling.

Usage::

    python3 website/check.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

WEBSITE = Path(__file__).resolve().parent
BOOK = WEBSITE / "book"
API = BOOK / "api"

# A page the landing overlay must have produced. If build.py stops copying
# content/index.html over mdBook's first chapter, the site silently loses its
# front page -- so assert on a string only the landing page carries.
LANDING_MARKER = "Give a guest an accelerator, not a driver."

# Pages the site must publish, independent of how SUMMARY.md is generated.
REQUIRED_PAGES = [
    "index.html",
    "getting-started.html",
    "api.html",
    "favicon.svg",
    "docs/specification.html",
    "docs/wire-abi.html",
    "docs/virtqueue.html",
    "docs/threat-model.html",
    "docs/architecture.html",
    "docs/portability.html",
    "docs/device-support-matrix.html",
    "docs/performance.html",
    "docs/public-api.html",
    "docs/release-policy.html",
    "docs/backend-implementer-guide.html",
    "docs/hexagon-operator-matrix.html",
    "docs/releases/v1.0.html",
]

# Tags that can carry a reference to another file, and the attributes on them
# that hold one. `srcset` is handled separately below because its value is a
# comma-separated candidate list, not a single URL.
REF_TAGS = "a|link|script|img|source|video|audio|embed|iframe|object|use|image|track"
TAG_RE = re.compile(rf"<(?:{REF_TAGS})\b([^>]*)>", re.IGNORECASE | re.DOTALL)
ATTR_RE = re.compile(
    r"""\b(href|src|data|poster)\s*=\s*(["'])(.*?)\2""",
    re.IGNORECASE | re.DOTALL,
)
SRCSET_ATTR_RE = re.compile(
    r"""\bsrcset\s*=\s*(["'])(.*?)\1""", re.IGNORECASE | re.DOTALL
)


def srcset_urls(value: str) -> list[str]:
    """Pull the URLs out of a ``srcset`` candidate list.

    ``srcset`` is ``url [descriptor]`` repeated, comma-separated -- so the whole
    attribute is not a URL and must not be resolved as one. Descriptors are
    whitespace-separated from the URL, which is why splitting on whitespace and
    taking the first field is enough.
    """
    urls = []
    for candidate in value.split(","):
        candidate = candidate.strip()
        if candidate:
            urls.append(candidate.split()[0])
    return urls


def references(html: str) -> list[str]:
    """Every same-document reference in the page, in source order."""
    found = []
    for attrs in TAG_RE.findall(html):
        for _, _, target in ATTR_RE.findall(attrs):
            found.append(target)
        for _, value in SRCSET_ATTR_RE.findall(attrs):
            found.extend(srcset_urls(value))
    return found


def site_pages() -> list[Path]:
    """Every HTML page the site itself generates, excluding the rustdoc tree.

    ``api/index.html`` is the exception: ``cargo doc --workspace`` does not emit
    a top-level index, so ``build.py`` writes that one itself and it is ours to
    check. The rest of ``api/`` is rustdoc's output.

    ``print.html`` is mdBook's concatenation of the whole book. Its links are
    the same ones already checked on the individual pages, but rebased in a way
    that makes false positives likely, so it is not crawled.
    """
    pages = [
        path
        for path in sorted(BOOK.rglob("*.html"))
        if API not in path.parents and path.name != "print.html"
    ]

    generated_api_index = API / "index.html"
    if generated_api_index.exists():
        pages.append(generated_api_index)

    return pages


def is_external(target: str) -> bool:
    parsed = urlparse(target)
    return bool(parsed.scheme or parsed.netloc)


def resolve(page: Path, target: str) -> Path | None:
    """Resolve a reference to a path inside ``book/``, or None if unresolvable.

    Returns the path that must exist. Directory targets resolve to their
    ``index.html``.
    """
    path_part = urlparse(target).path
    if not path_part:
        return None

    decoded = unquote(path_part)
    if decoded.startswith("/"):
        resolved = BOOK / decoded.lstrip("/")
    else:
        resolved = page.parent / decoded

    if decoded.endswith("/"):
        resolved = resolved / "index.html"

    return resolved


def check_references(pages: list[Path], api_built: bool) -> list[str]:
    problems: list[str] = []

    for page in pages:
        rel_page = page.relative_to(BOOK).as_posix()
        html = page.read_text(encoding="utf-8", errors="replace")

        for target in references(html):
            target = target.strip()
            if not target or target.startswith(("#", "data:", "mailto:")):
                continue
            if is_external(target):
                continue

            resolved = resolve(page, target)
            if resolved is None:
                continue

            # A root-relative "/" is the deployed site root, which is
            # index.html; that is covered by REQUIRED_PAGES.
            if resolved == BOOK:
                continue

            try:
                inside = resolved.resolve().relative_to(BOOK.resolve())
            except ValueError:
                problems.append(f"{rel_page}: link escapes the site root: {target}")
                continue

            if not api_built and inside.parts[:1] == ("api",):
                continue

            if not resolved.exists():
                problems.append(f"{rel_page}: dangling reference {target!r}")

    return problems


def main() -> int:
    problems: list[str] = []

    if not BOOK.is_dir():
        print(
            "error: website/book/ does not exist -- run website/build.py first",
            file=sys.stderr,
        )
        return 1

    for rel in REQUIRED_PAGES:
        if not (BOOK / rel).exists():
            problems.append(f"missing required page: {rel}")

    index = BOOK / "index.html"
    if index.exists():
        if LANDING_MARKER not in index.read_text(encoding="utf-8", errors="replace"):
            problems.append(
                "index.html is not the standalone landing page -- the overlay in "
                "build.py did not run, or content/index.html changed"
            )

    api_built = (API / "index.html").exists()
    if not api_built:
        print("note: book/api/ is absent, skipping rustdoc link targets")

    pages = site_pages()
    problems.extend(check_references(pages, api_built))

    if problems:
        print(f"\n{len(problems)} problem(s) in website/book/:\n", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    print(f"ok: {len(pages)} page(s) checked, no dangling references")
    return 0


if __name__ == "__main__":
    sys.exit(main())
